# Site settings
title: ka_tech
email: kahoau@domain.com
description: > # this means to ignore newlines until "baseurl:"
    facebook: https://www.facebook.com/kahoau
    linkedin: http://hk.linkedin.com/in/kahoau
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kahoau.github.io" # the base hostname & protocol for your site
twitter_username: kahoau
github_username:  kahoau



# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8

github: https://github.com/kahoau